### ISSUE TITLE
[FEATURE] Add consent screen

### ISSUE THREAD

**Issue by peilingjiang** [EasyEyes/threshold#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://docs.google.com/spreadsheets/d/1x65NjykMm-XUOz98Eu_oo6ON2xspm_h0Q0M2u6UGtug/edit#gid=1385703808
See EasyEyes Manual Web sheet for explanation fo how the consent form and fonts should be handled. We need to allow the scientist to upload any number of consent forms and fonts to the ConsentForms and Fonts folders in an EasyEyesResources folder in the scientist's Pavlovia account. The file names will later be specified as values of the _consentForm and targetFont parameters.

Use the value of _consentForm to select a file from EasyEyesResources/ConsentForms/ in the scientist's Pavlovia account. The preprocessor will check that there is a match before uploading threshold.js to Pavlovia. I'm not sure what file formats we should support for the consent document. Markdown is good for reflowing the lines to adapt to various screens sizes. PDF is good for showing a stamped document. Probably Markdown is the more robust solution. Threshold.js will need to flow the text so it's easy to read even on a small screen. The validity of our consent "signatures" could be challenged unless it's easy to read the consent form.

**Additional context**

**Comment by svr8** [comment]
search `if (useRC)` and the component should be above this
