### ISSUE TITLE
[FEATURE] Put up web page https://easyeyes.app/threshold

### ISSUE THREAD

**Issue by denispelli** [EasyEyes/threshold#17]
PUT UP THE THRESHOLD PAGE. Let's implement the bare bones user interface of https://easyeyes.app/threshold/ . Create a threshold.html web page in the EasyEye.app directory. It should have the same menu bar as the rest of the pages in the easyeyes.app directory. For the time being, the common menu bar will NOT mention "Threshold". So the public won't easily find our page. I realize that Google will track it, but we don't need high security. Right now I imagine:
• Menu bar, consistent with rest of EasyEyes.app
• Easy uploading of a Threshold table to the EasyEyes directory. Uploading immediately begins the preprocessor.
• A radio button selecting whether to run the preprocessor WITHOUT requiring a Pavlovia account.
• A radio button selecting whether or not to enable automatic upload to Pavlovia. (Grayed out if scientist selected to run without pavlovia.)
• Once the preprocessor runs, it should display a page of errors that can be saved to disk as a plain text file, possibly with Markdown formatting.
• If and when the preprocessor finds no errors, and "automatic upload" is on, upload files to a new project in the scientist's Pavlovia account, and display a copyable display of the URL of the uploaded experiment. Label it:
**URL to run your uploaded experiment:**
• Note that any uploading to Pavlovia will require OAuth logging into Pavlovia. 
The preprocessor will check that any required consent forms and fonts are present in Pavlovia.

As a friendly gesture to visitors who may not yet have Pavlovia accounts, we offer the option of preprocessing WITHOUT Pavlovia to allow the scientist to see whatever error messages the preprocessor produces. However, we should NOT allow uploading to pavlovia until the preprocessor has checked the table's specified fonts and consents against those available in the EasyEyesResources folder of their Pavlovia site.

**Comment by denispelli** [comment]
ADD HANDLING OF FONTS AND CONSENTS. 
In easyeyes/threshold, add user interface elements for easy uploading of a few consent forms and Fonts to the EasyEyesResources/Consents and EasyEyesResources/Consents folders in the scientist's Pavlovia account, and an easy way to get (popup?) directories of both folders. (This will require OAuth login to the scientist's Pavlovia account.) The popup directories must allow selection and copying of the file names to the clipboard. We must provide a way to delete a file from either folder. 1 day.

**Comment by aburchell** [comment]
Just so we don't accidentally spend time recreating anything, the Javascript translation of the preprocessor can be found in the [control-panel (private) repo](https://github.com/EasyEyes/control-panel). At the moment, it just does 
> • Easy uploading of a Threshold table to the EasyEyes directory. Uploading immediately begins the preprocessor.

I think we should keep using that other repo (renaming if desired) for development of this experimenter-facing side of things (ie not in the Threshold repo). The web-page itself will need to be in the website repo.  @peilingjiang do I remember correctly that you did something similar for the remote calibrator, ie develop in its own repo, then embed the repo w/in the website repo?

**Comment by aburchell** [comment]
> ADD HANDLING OF FONTS AND CONSENTS to the EasyEyes.app/threshold web page.
> In easyeyes/threshold, add user interface elements for easy uploading of a few consent forms and Fonts to the EasyEyesResources/Consents and EasyEyesResources/Consents folders in the scientist's Pavlovia account, and an easy way to get (popup?) directories of both folders. (This will require OAuth login to the scientist's Pavlovia account.) The popup directories must allow selection and copying of the file names to the clipboard. We must provide a way to delete a file from either folder. 1 day.

We probably ought to create a new "issue" for every feature request. We can only close the issue as a whole, afaik, so adding new requests in the thread will make the current state of affairs less obvious.

**Comment by denispelli** [comment]
Dear Gus
I understand, but even though fonts and consent forms are distinct
categories, it's the same code. The only difference is the instruction and
the destination folder.

I think it's fine to have feature requests, but I'm finding them nearly
useless for project management, as they do not provide a useful display of
how we're doing. Until something better appears, I'm going back to my excel
spreadsheet, which i can sort in various ways and provides a compact useful
display of our status.
Best
Denis


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University

+1-646-258-7524 | ***@***.***

http://psych.nyu.edu/pelli/ | Skype: denispelli <#>
| http://denispelli.com
<https://www.facebook.com/denispelli>
<https://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>
‌

**Comment by denispelli** [comment]
Dear Gus
Thx for the heads up. This seems needlessly complicated. The main point of
a repo is to make it easy to find things. The preprocessor is an essential
part of the project. I'd like to keep the threshold project in the
threshold repo. Ok?
Am I missing something?
Best
Denis


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University

+1-646-258-7524 | ***@***.***

http://psych.nyu.edu/pelli/ | Skype: denispelli <#>
| http://denispelli.com
<https://www.facebook.com/denispelli>
<https://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>
‌

**Comment by aburchell** [comment]
> Dear Gus I understand, but even though fonts and consent forms are distinct categories, it's the same code. The only difference is the instruction and the destination folder. I think it's fine to have feature requests, but I'm finding them nearly useless for project management, as they do not provide a useful display of how we're doing. Until something better appears, I'm going back to my excel spreadsheet, which i can sort in various ways and provides a compact useful display of our status. Best Denis [image: photo] *Denis Pelli* Professor of Psychology & Neural Science, New York University +1-646-258-7524 | ***@***.*** http://psych.nyu.edu/pelli/ | Skype: denispelli <#> | http://denispelli.com <https://www.facebook.com/denispelli> <https://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli> ‌
> […](#)

I apologize, I should have been more clear. I didn't mean that the fonts and consents should be different issues, but that "ADD HANDLING OF FONTS AND CONSENTS" should be it's own issue from "PUT UP THE THRESHOLD PAGE". Excel seems to work great for you, but for me as a developer Github is much more useful. It sounds like what you're looking for is the [Project page](https://github.com/orgs/EasyEyes/projects/2#card-69137194), which provides a table of relevant Issues and their state (ie To Do/In progress/Complete). I would ask that you not abandon the workflow -- which we have all agreed on, and have only just started using -- because I made a request for the sake of making progress clear (ie represent separate tasks as separate Issues).

**Comment by aburchell** [comment]
> Dear Gus Thx for the heads up. This seems needlessly complicated. The main point of a repo is to make it easy to find things. The preprocessor is an essential part of the project. I'd like to keep the threshold project in the threshold repo. Ok? Am I missing something?

No, I think you're right. There is some developer-side benefit (or maybe just personal preference) with having a separate repo, but @peilingjiang has shown me a way (using [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)) that we can have those benefits while still including the files in the Threshold repo as you request. Peiling said he will take care of this, and start on the page you initially requested, today.

**Comment by denispelli** [comment]
Great! Perfect. Thx to you and Peiling.
Denis

On Mon, Sep 20, 2021 at 1:55 PM Gus Burchell ***@***.***>
wrote:

> Dear Gus Thx for the heads up. This seems needlessly complicated. The main
> point of a repo is to make it easy to find things. The preprocessor is an
> essential part of the project. I'd like to keep the threshold project in
> the threshold repo. Ok? Am I missing something?
>
> No, I think you're right. There is some developer-side benefit (or maybe
> just personal preference) with having a separate repo, but @peilingjiang
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_peilingjiang&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=AR-wUj7R66Y2wQJDqvgTIvYDHSmZWkRetdjZELP3UXs&e=>
> has shown me a way (using submodules
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__git-2Dscm.com_book_en_v2_Git-2DTools-2DSubmodules&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=qDFRCGTuuxTw-KecQ5Iy6mRfVvZa4OpAD7tD8KgPzWw&e=>)
> that we can have those benefits while still including the files in the
> Threshold repo as you request. Peiling said he will take care of this, and
> start on the page you initially requested, today.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EasyEyes_threshold_issues_17-23issuecomment-2D923148585&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=kckhMvtFHpepgEWW8AtuOZ4yINm9flcbHwF6q-uM2rE&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADKWX6ZMTDIA3WMO7PW65VDUC5YRVANCNFSM5EKUCYOA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=PTEuLT9YA0hlhTQu7WorDlksZMQG56VNq9-IMUZ6AZw&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=f8DfqW_6nedxGYV12ol61DV-HjCB93KVg2fHQAiYSBw&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=kdlp84k9mZ_k0b-XZXOyCXHh1CqP9H-NPrCYs6HyV2c&s=jf5eo3Lyn4dURjp3M8wysH1r9GoEeoekQD2U9vmZbOQ&e=>.
>
>
-- 

Denis Pelli
Professor of Psychology & Neural Science, New York University
+1-646-258-7524  | ***@***.***
http://psych.nyu.edu/pelli/  | Skype: denispelli
| http://denispelli.com

Sent from my iphone.

**Comment by denispelli** [comment]
Hi. Thx
1. Yes. The web page is a separate issue. Good catch.  Can you spilt it off?
2. My frustration was with the unhelpful issue display not your comment
which was helpful.  3. I’ll look at the project page. Sounds perfect.
 Thx

On Mon, Sep 20, 2021 at 1:30 PM Gus Burchell ***@***.***>
wrote:

> Dear Gus I understand, but even though fonts and consent forms are
> distinct categories, it's the same code. The only difference is the
> instruction and the destination folder. I think it's fine to have feature
> requests, but I'm finding them nearly useless for project management, as
> they do not provide a useful display of how we're doing. Until something
> better appears, I'm going back to my excel spreadsheet, which i can sort in
> various ways and provides a compact useful display of our status. Best
> Denis [image: photo] *Denis Pelli* Professor of Psychology & Neural
> Science, New York University +1-646-258-7524 | *@*.***
> http://psych.nyu.edu/pelli/ | Skype: denispelli <#> |
> http://denispelli.com
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__denispelli.com&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=x1JYIKKfAvLD6z3cSQAt7NE5JGZF3FtiuZaIAnZTVJw&e=>
> https://www.facebook.com/denispelli
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_denispelli&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=FCuLTPwngVCEjZ0sEV6A8tsy4PtWFpmsnhg_ggLQXDA&e=>
> https://www.linkedin.com/in/denispelli/
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__www.linkedin.com_in_denispelli_&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=wis8WBMlwNrIehFqtfRO65rINfT4LNreCIIN9gqYgXU&e=>
> http://twitter.com/denispelli
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__twitter.com_denispelli&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=iGGcyVqRR96zYVQax4W3l6Kmo72J95dsEqDiKL1Etb8&e=>
> ‌
> … <#m_-7268510677576128810_>
>
> I apologize, I should have been more clear. I didn't mean that the fonts
> and consents should be different issues, but that "ADD HANDLING OF FONTS
> AND CONSENTS" should be it's own issue from "PUT UP THE THRESHOLD PAGE".
> Excel seems to work great for you, but for me as a developer Github is much
> more useful. It sounds like what you're looking for is the Project page
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_orgs_EasyEyes_projects_2-23card-2D69137194&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=t_EykKlYY0rGEowrIhdp2IQuxmaU7txnq935HYtwgvI&e=>,
> which provides a table of relevant Issues and their state (ie To Do/In
> progress/Complete). I would ask that you not abandon the workflow -- which
> we have all agreed on, and have only just started using -- because I made a
> request for the sake of making progress clear (ie represent separate tasks
> as separate Issues).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EasyEyes_threshold_issues_17-23issuecomment-2D923131884&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=KZ1R2copZPx-4Im3ymGmrXtYBKcjpQ_wFbgU9Udx01o&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADKWX67RPOSLQJXUSDQTAYLUC5VTPANCNFSM5EKUCYOA&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=NlbB2F87qA_FH93AeSYQ0oxAdi77vkni9yIsyTfYvcQ&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=asAv8Y-rkoDblcg63pu5wX0Jv1voEbLYpHeNSS1CUH0&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=ZFbMdYrajUOSWqpDTrPzrDRQFYtwP8m7FvdeNYi5DoM&s=T8ssgQJLaIURYUk5Kc8kmZmVLg0b9weRfmfPKG0AMrc&e=>.
>
>
-- 

Denis Pelli
Professor of Psychology & Neural Science, New York University
+1-646-258-7524  | ***@***.***
http://psych.nyu.edu/pelli/  | Skype: denispelli
| http://denispelli.com

Sent from my iphone.
