### ISSUE TITLE
[FEATURE] Get Keypad to work with Threshold

### ISSUE THREAD

**Issue by peilingjiang** [EasyEyes/threshold#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As documented in the Threshold Manual Inputs sheet, 
https://docs.google.com/spreadsheets/d/1x65NjykMm-XUOz98Eu_oo6ON2xspm_h0Q0M2u6UGtug/edit#gid=2021552264
**inclusion of the Keypad should be controlled by the parameter 
easyEyesSimulateKeypadBool**

**Additional context**

**Comment by denispelli** [comment]
THis is very old. The keypad now works very well, but with a different parameter. Closed.
