### ISSUE TITLE
[FEATURE] Restrict maximum spacing when measuring a spacing threshold.

### ISSUE THREAD

**Issue by peilingjiang** [EasyEyes/threshold#7]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by aburchell** [comment]
### About the issue
If a participant does poorly early on in a study, QUEST will suggest massive letter sizes. This causes stimuli to overlap with each other and/or fixation, or extend beyond the screen. The goal is to have stimuli be presented at up-to, but not exceeding, the maximum size at which all stimuli can be presented correctly.
