### ISSUE TITLE
[BUG] Text is positioned off-center

### ISSUE THREAD

**Issue by minjungkim85** [EasyEyes/threshold#77]
When I have multiple blocks of the reading test, the text is sometimes positioned off-center. The bug only occurs when I use the attached [ex.txt](https://github.com/EasyEyes/threshold/files/12807545/ex.txt) as the reading corpus, and only for block #3 or later.

**Comment by denispelli** [comment]
dear mj
Thx.
can you provide a spreadsheet for the experiment?
Best
Denis

**Comment by minjungkim85** [comment]
Sure! Here it is.

[fontsizeTest.csv](https://github.com/EasyEyes/threshold/files/12838363/fontsizeTest.csv)

**Comment by denispelli** [comment]
https://trello.com/c/9fSnql0G
