### ISSUE TITLE
[BUG]When running a new experiment table the corpus is not proper

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#84]
**Describe the bug**

Created a new reading experiment but the reading corpus is not looking as expected

**To Reproduce**

Add the below table to examples folder.
Run npm run examples
run npm start -- --name=easyeyes_buggy_1
[easyeyes_buggy_1.csv](https://github.com/user-attachments/files/16181663/easyeyes_buggy_1.csv)

**Expected behavior**

The reading corpus should be clear

**Screenshots**

![Screenshot from 2024-07-11 10-33-57](https://github.com/EasyEyes/threshold/assets/117389237/69848191-4d8e-40a0-b983-994ba3e1d203)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by denispelli** [comment]
Dear sravyam
Thanks for the bug reports. Can I share a tip? The best way to share an
experiment is to “export” it. Once you’re compiler your experiment,
EasyEyes displays an “Export” button on the main compiler page. Pressing
that button creates an export.zip file in your Downloads folder. The zip
includes the spreadsheet and all other resources required to run the
experiment (e.g. fonts and corpuses). The file is called NAME.export.zip,
where NAME is your experiment name. If you receive such a file you can open
it and use the pieces individually, or you can feed the intact zip to
EasyEyes which will compile and run it, without saving the resources to
Pavlovia. We recommend to everyone filing bug reports to include the
export.zip file, making it easy for a programmer to replicate the bug and
work on it.
Best
Denis

**Comment by sravyam28** [comment]
Hi Denis,
Thanks for letting me know. Do you think it would be the same if I can zip the compiled experiment folder from examples and attach it here? I work on the experiments directly from threshold repo and not from Pavlovia but if it is the same I can attach it from my repo after compiling it.

**Comment by denispelli** [comment]
Oh. Yes. Sure. Just include all needed resources with the experiment spreadsheet. They ought to work. However the other day I opened an export zip edited the experiment and rezipped it, expecting it to work but the compiler went haywire. My hunch is that there are multiple zip formats and our compiler is not compatible with the macOS finder’s zipping. It wasn’t a matter of failing to unzip. It “unzipped” and complained about weird resource problems. So it would be a subtle failure. Alas the person who wrote the export/import code just left for greener pastures. So it will be a while before I can put someone on it.  So, yes, let’s try what you suggest but we might need to try several zippers before we find one compatible with the EasyEyes compiler. BestDenis Denis PelliProfessor of Psychology & Neural Science, New York University+1-646-258-7524  ***@***.***://psych.nyu.edu/pelli/  | Skype: denispelli| http://denispelli.comSent from my iPhoneOn Jul 11, 2024, at 8:58 PM, sravyam28 ***@***.***> wrote:﻿
Hi Denis,
Thanks for letting me know. Do you think it would be the same if I can zip the compiled experiment folder from examples and attach it here? I work on the experiments directly from threshold repo and not from Pavlovia but if it is the same I can attach it from my repo after compiling it.

**Comment by sravyam28** [comment]
attaching zip file
[easyeyes_buggy_1.zip](https://github.com/user-attachments/files/16286798/easyeyes_buggy_1.zip)

**Comment by sravyam28** [comment]
Hi @denispelli  I updated a zip file of the build folder, can you please check and let me know.
Also the issue is also seen in the readingExperiment in examples so it can be reproduced even without my tables.

**Comment by sravyam28** [comment]
Hi @denispelli Thanks for the fix and update. With the latest main branch (on commit d80976493ae2c081f12fa4b32fe2c134a749bc0b) I see the corpus is far up in the screen below is the screenshot of how it looks. Can we know if any param in the table used in this case needs to be changed for correct corpus.
 [easyeyes_buggy_1.csv](https://github.com/user-attachments/files/16181663/easyeyes_buggy_1.csv) 
![453600282_447365671626388_8035444405185950226_n](https://github.com/user-attachments/assets/31b12cb2-27cf-4d3d-94d9-8f7d90ff6592)
