### ISSUE TITLE
[BUG]Created a new reading experiment but corpus is not visible when screen color is black

### ISSUE THREAD

**Issue by sravyam28** [EasyEyes/threshold#85]
**Describe the bug**

When the screen color is set to black and font color is set to white the corpus is not visible but the instructions are visible

**To Reproduce**

Add the below table to examples folder.
Run npm run examples
run npm start -- --name=easyeyes_buggy
[easyeyes_buggy.csv](https://github.com/user-attachments/files/16181646/easyeyes_buggy.csv)

**Expected behavior**

The reading corpus should be clear

**Screenshots**
![Screenshot from 2024-07-11 10-47-47](https://github.com/EasyEyes/threshold/assets/117389237/477e2889-45a0-436a-8ec4-62bda04af912)
![Screenshot from 2024-07-11 10-48-27](https://github.com/EasyEyes/threshold/assets/117389237/d2f17451-853c-4513-a79b-0f7aa8076c71)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sravyam28** [comment]
attaching zip file for example build
[easyeyes_buggy.zip](https://github.com/user-attachments/files/16286794/easyeyes_buggy.zip)

**Comment by sravyam28** [comment]
Hi @denispelli  I updated a zip file of the build folder, can you please check and let me know.
Also the issue is also seen in the readingExperiment in examples so it can be reproduced even without my tables.

**Comment by aburchell** [comment]
@sravyam28 @denispelli The Reading paragraph should now correctly reflect the color specified in `markingColorRGBA` 👍
